### ISSUE TITLE
Limit to pulled messages

### ISSUE THREAD

**Issue by zecamigo** [itprojects/InboxPager#24]
It would be great if there was an option to limit the number of messages pulled.

**Comment by zecamigo** [comment]
I have over 20k unread messages in my mail account!

**Comment by itprojects** [comment]
This will be difficult to implement and support. As you can read in the WON'T FIX section of the Readme.md: the app is "lite". It is designed as a (message) pager, that notifies the user of a change in the inbox, with the ability to reply in a quick way.

A Solution to your 20k messages. is to please archive your emails through your email server's web interface. You probably don't re-read them every day.

As for the unread messages - managing the unread messages is currently buggy, because of the introduction of the sidebar in the new UI (v4.0). There is a menu called "Mark All Read" that should remove the individual message unread flags.

Note:
Messages downloaded from the server inbox usually follow the order or arrival - latest will be near the top, first will be at the bottom of the list. This can be different (and hence the unread status) IF a message is moved in and out of the inbox folder of the IMAP folders.
