### ISSUE TITLE
GMail Receiving SMTP OpenSSLECPublicKey cannot be cast to RSAPublicKey

### ISSUE THREAD

**Issue by juliolopeztorres** [itprojects/InboxPager#34]
Hi there!

First thing first, thank you for sharing your code and your app.

I have been using your software for some past months and now it is starting to fail. The main issue I have is when trying to refresh my inbox using a GMail account. 

2 weeks ago, I started to received the following message when I try to resfresh the inbox:

```
com.android.org.conscrypt.OpenSSLECPublicKey cannot be cast to java.security.interfaces.RSAPublicKey
```
I think this could be related to certificates. Maybe in
`https://github.com/itprojects/InboxPager/blob/master/InboxPager/src/main/java/net/inbox/server/SocketIO.java#L148`

I have certainly not changed my GMail configuration. Did you notice any change from Google Services itself?

Do you have any clue?

Thank you!

**Comment by itprojects** [comment]
@juliolopeztorres Thanks for reporting this bug!

There was a small chance that the patched (v4.4) Inbox Pager would have already been made available, but the server hasn't picked it up yet. See commit aebdfa36a .

One quick way of fixing this is to use the test build, for a week or two. This would require an uninstall of the official repository app and then install from the test [APK](https://github.com/itprojects/InboxPager/blob/apk-debug/InboxPager-444-2.apk). Alternatively if you know how to code, pull that commit and produce your own audited apk.

After the app is updated on the server, you may have to repeat the repository switch with the official one.

This bug is on account of a casting error. Gmail certificates (elliptic curves now?) seem to have changed in March of 2020.
